/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package question3;

import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author 19342975
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    
    //Variables used for handling the files
    File myFile = new File("employees.txt");
    Scanner fileReader;
    Scanner fileReaderTwo;
    Scanner fileReaderThree;
    
    public Employees() {
        //Making the file if it does not exist already
        prepareFile(myFile);
        
        initComponents();
    
        //Populating the text area
        getEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblEmployeeName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        lblEmployeeEmail = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEmployees = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Form");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adding new employee", 0, 0, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setToolTipText("");

        lblEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmployeeID.setText("Employee ID:");

        txtEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmployeeName.setText("Employee Name:");

        txtEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblEmployeeEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmployeeEmail.setText("Employee Email:");

        txtEmployeeEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmployeeID)
                    .addComponent(txtEmployeeName)
                    .addComponent(txtEmployeeEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeID)
                            .addComponent(lblEmployeeName)
                            .addComponent(lblEmployeeEmail))
                        .addGap(0, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployeeID)
                .addGap(18, 18, 18)
                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmployeeName)
                .addGap(18, 18, 18)
                .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmployeeEmail)
                .addGap(18, 18, 18)
                .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtEmployees.setColumns(20);
        txtEmployees.setRows(5);
        jScrollPane2.setViewportView(txtEmployees);
        txtEmployees.setEditable(false);

        jLabel4.setText("Employees on file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //Adding a new employee to the file
        try {
                        
            if (!txtEmployeeID.getText().equals("") && !txtEmployeeName.getText().equals("") && !txtEmployeeEmail.getText().equals("")){
                //Reading the file
                fileReaderTwo = new Scanner(new File("employees.txt"));

                //variable used to store what is already in the file
                StringBuilder previousEmployees = new StringBuilder();

                //Getting the informtion that is in the file
                String id = "";
                String name = "";
                String email = "";
                while(fileReaderTwo.hasNext()){
                    id = fileReaderTwo.nextLine();
                    name = fileReaderTwo.nextLine();
                    email = fileReaderTwo.nextLine();

                    previousEmployees.append(id + "\r\n");
                    previousEmployees.append(name + "\r\n");
                    previousEmployees.append(email + "\r\n");                               
                }

                //Variables containing the information about the new employee
                String employeeID = txtEmployeeID.getText();
                String employeeName = txtEmployeeName.getText();
                String employeeEmail = txtEmployeeEmail.getText();

                //Appending to the text area
                txtEmployees.append("ID: " + employeeID + "\n");
                txtEmployees.append("NAME: " + employeeName + "\n");
                txtEmployees.append("EMAIL: " + employeeEmail + "\n");

                //Adding the new employee to the previousEmployee variable
                previousEmployees.append(employeeID + "\r\n");
                previousEmployees.append(employeeName + "\r\n");
                previousEmployees.append(employeeEmail + "\r\n");            

                //FileWriter object
                FileWriter writer = new FileWriter(new File("employees.txt"));

                //Writing to the file
                writer.write(previousEmployees.toString());
                writer.flush();
                writer.close();

                JOptionPane.showMessageDialog(null, "New employee added to file");
                
                //clearing the text fields
                txtEmployeeID.setText("");
                txtEmployeeName.setText("");
                txtEmployeeEmail.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Some of the fields are empty please fill them in", "Empty Fields", JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            //Getting the id from the user
            String userInput = JOptionPane.showInputDialog(null, "Enter the employee ID");
            
            //Reading thew file
            fileReaderThree = new Scanner(new File("employees.txt"));
            
            String id = "";
            String name = "";
            String email = ""; 
            boolean found = false;
            while(fileReaderThree.hasNextLine()){
                id = fileReaderThree.nextLine();
                name = fileReaderThree.nextLine();
                email = fileReaderThree.nextLine();
                
                
                
                if (id.equals(userInput)){
                    found = true;
                    JOptionPane.showMessageDialog(null, "EMPLOYEE FOUND\n" + "Name: " + name + "\nEmail: " + email);
                    break;
                }else{
                    found = false;
                }
            }
            //Checking if the user use found
            if(!found){
                JOptionPane.showMessageDialog(null, "Employee not found");
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }
    
    //methods used by the program
    public void prepareFile(File file){
        try {
            if(file.exists()){
                System.out.println("file exists already");
            }else if(file.createNewFile()){
                System.out.println("file created");
            }
        } catch (Exception e) {
        }
    }
    
    public void getEmployees(){
        //trying to read the file
        try {
            //Reading the file
            fileReader = new Scanner(new File("employees.txt"));
            
            String id = "";
            String name = "";
            String email = "";
            
            while(fileReader.hasNext()){
                id = fileReader.nextLine();
                name = fileReader.nextLine();
                email = fileReader.nextLine();
                
                //Displaying the employees to the text area
                txtEmployees.append("ID: " + id + "\n");
                txtEmployees.append("NAME: " + name + "\n");
                txtEmployees.append("EMAIL: " + email + "\n\n");
                
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Could not access the file\n" + e.getMessage());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployeeEmail;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextArea txtEmployees;
    // End of variables declaration//GEN-END:variables
}
